# Generated by Django 3.1.12 on 2026-03-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_airecommendation_sellerrating_sellertrustscore_smartoffer_userbehavior_virtualtryon_voicesearch_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Credit/Debit Card'), ('upi', 'UPI Payment'), ('paytm', 'Paytm Wallet'), ('razorpay', 'Razorpay'), ('stripe', 'Stripe')], default='cod', max_length=20),
        ),
    ]
