# Generated by Django 3.1.12 on 2026-04-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Order Placed'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return_requested', 'Return Requested'), ('failed', 'Payment Failed'), ('success', 'Success')], default='pending', max_length=50),
        ),
    ]
