# Generated by Django 3.1.12 on 2026-04-05 10:15

from django.db import migrations, models


def update_success_to_delivered(apps, schema_editor):
    """Update existing 'success' orders to 'delivered'"""
    Order = apps.get_model('store', 'Order')
    Order.objects.filter(status='success').update(status='delivered')


def reverse_update_success_to_delivered(apps, schema_editor):
    """Reverse: change 'delivered' back to 'success'"""
    Order = apps.get_model('store', 'Order')
    Order.objects.filter(status='delivered').update(status='success')


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_add_return_requested_status'),
    ]

    operations = [
        # First update existing data
        migrations.RunPython(update_success_to_delivered, reverse_update_success_to_delivered),
        
        # Then alter the field choices
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Order Placed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return_requested', 'Return Requested')], default='pending', max_length=50),
        ),
    ]
